# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
#
os:
  editPreset: nvim-remote
gui:
  showRandomTip: false
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#f5c2e7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#f5c2e7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"

disableStartupPopups: true

git:
  autoFetch: false
  log:
    order: default
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side
    useConfig: false
  commit:
    signOff: false
  parseEmoji:
    true
    # externalDiffCommand: difft --color=always

update:
  method: never
