# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
gui:
  showFileTree: false # for rendering changes files in a tree format

git:
  paging:
    colorAarg: always
    pager: delta --paging=never --color-only
