# yaml-language-server: $schema=./schema.json
gui:
  showFileTree: false # for rendering changes files in a tree format
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"


git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
    externalDiffCommand: difft --color=always

services:
  gitlab.tech.dnb.no: 'gitlab:gitlab.tech.dnb.no'

update:
  method: never
