# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
#
os:
  editPreset: nvim-remote
gui:
  showRandomTip: false
  shortTimeFormat: "15:04"
  nerdFontsVersion: "3"

disableStartupPopups: true

git:
  autoFetch: true
  log:
    order: default
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
  commit:
    signOff: false
  parseEmoji: true
    # externalDiffCommand: difft --color=always

update:
  method: never
