return {
  {
    'm4xshen/hardtime.nvim',
    dependencies = { 'MunifTanjim/nui.nvim', 'nvim-lua/plenary.nvim' },
    opts = {
      enabled = false,
      disabled_filetypes = {
        'fish',
        'NvimTree',
        'TelescopePrompt',
        'aerial',
        'alpha',
        'checkhealth',
        'dapui*',
        'Diffview*',
        'Dressing*',
        'help',
        'httpResult',
        'lazy',
        'lspinfo',
        'Neogit*',
        'mason',
        'neotest%-summary',
        'minifiles',
        'neo%-tree*',
        'netrw',
        'noice',
        'notify',
        'prompt',
        'qf',
        'query',
        'oil',
        'undotree',
        'trouble',
        'Trouble',
        'fugitive',
      },
    },
  },
}
