[keys]
move_up = ["k", "<up>"]
move_down = ["j", "<down>"]
move_left = ["<left>"]
move_right = ["<right>"]
select_focus = ["l", "<enter>"]
close_parent = ["h", "<backspace>"]
select_parent = ["p"]
select_first = ["g", "<home>"]
select_last = ["G", "<end>"]
change_root = ["r"]
reset = ["<esc>"]
page_up = ["<page-up>", "<ctrl-u>"]
page_down = ["<page-down>", "<ctrl-d>"]
change_layout = ["v"]
tree_scale_up = ["["]
tree_scale_down = ["]"]
switch = ["<tab>"]
edit = ["e"]
copy_name = ["y"]
copy_value = ["Y"]
filter = ["/"]
filter_key = ["?"]
filter_value = ["*"]
filter_next_match = ["n"]
filter_prev_match = ["N"]
filter_switch_ignore_case = ["I"]
expand_children = ["x"]
expand_all = ["X"]
show_help = ["<f1>"]
quit = ["<ctrl-c>", "q"]
